port = 3000

[bee]
image = "ethersphere/bee:2.5.0"
password = "some-password"
welcome_msg = "Hello, Swarm!"
full_node = true
swap_enable = true
reserve_doubling = false

[network]
nat_addr = "1.1.1.1"
api_port = "17xx"
p2p_port = "18xx"
use_docker_host = false

[chains]
eth_rpc = "https://some.rpc"
gno_rpc = "https://some.rpc"

[storage]
root_path = "/media"
parent_dir_format = "swarm_data_xx"
parent_dir_capacity = 4
