[bee]
image = "ethersphere/bee:2.5.0"
password_path = "/var/lib/bee/password"
welcome_msg = "Hello, Swarm!"

[network]
nat_addr = "1.1.1.1"
api_port = "17xx"
p2p_port = "18xx"

[chains]
eth_rpc = "https://some.rpc"
gno_rpc = "https://some.rpc"

[storage]
root_path = "/media"
parent_dir_format = "swarm_data_xx"
parent_dir_capacity = 4
